services:
  postgres:
    image: postgres:17
    container_name: orderflow-postgres
    environment:
      POSTGRES_USER: orderflow
      POSTGRES_PASSWORD: orderflow
      POSTGRES_DB: orderflow
    ports:
      - "5432:5432"
    volumes:
      - orderflow-data:/var/lib/postgresql/data

volumes:
  orderflow-data: